Raise explicit error when `hmac_secret` is not set but is required
Some features such as webauthn and active_sessions require `hmac_secret`
to be set, but raise a cryptic:

  TypeError: no implicit conversion of nil into String

Since it's not clear from this that the issue is in `hmac_secret`
being unset, we change this to raise an explicit `ArgumentError`.